### ISSUE TITLE
SublimeREPL integration

### ISSUE THREAD

**Issue by igoradamenko** [tonsky/sublime-clojure#2]
Hey Nikita!

I'm rolling into Clojure and setting up dev env, and I've heard in your talk on Clojure/north in Toronto the story about this package. That's why I've installed it. But SublimeREPL doesn't work with it by default. It runs `lein repl` in background, opens new tab for `*REPL* [clojure]`, however when I send any selected code there it says it can't find a REPL for `clojurec`.

I've fixed this by defining user configs for Sublime REPL inside `~/Library/Application Support/Sublime Text 3/Packages/User/SublimeREPL/config/Clojure`. I've added `Main.sublime-menu`:

```json
[
     {
        "id": "tools",
        "children":
        [{
            "caption": "SublimeREPL",
            "mnemonic": "R",
            "id": "SublimeREPL",
            "children":
            [
                {"caption": "Clojure",
                 "id": "Clojure",
                 "children":[
                    {"command": "repl_open", 
                     "caption": "ClojureC",
                     "id": "repl_clojurec",
                     "args": {
                        "type": "subprocess",
                        "encoding": "utf8",
                        "cmd": {"windows": ["lein.bat", "repl"],
                                "linux": ["lein", "repl"],
                                "osx":  ["lein", "repl"]},
                        "soft_quit": "\n(. System exit 0)\n",
                        "cwd": {"windows":"c:/Clojure",
                                "linux": "$file_path",
                                "osx": "$file_path"},
                        "syntax": "Packages/sublime-clojure/ClojureC.tmLanguage",
                        "external_id": "clojurec",
                        "extend_env": {"INSIDE_EMACS": "1"}
                        }
                    }]
                }
            ]   
        }]
    }
]
```

And `Default.sublime-commands`:

```json
[
    {
        "caption": "SublimeREPL: ClojureC",
        "command": "run_existing_window_command", "args":
        {
            "id": "repl_clojurec",
            "file": "config/Clojure/Main.sublime-menu"
        }
    },
]
```

They defines new REPL as `clojurec` and also applies `sublime-clojure` to it. 

Now REPL for ClojureC is available in menu:

<img width="545" alt="Captura de pantalla 2019-09-16 a las 16 48 27" src="https://user-images.githubusercontent.com/6537798/64963454-f3047280-d8a1-11e9-91cc-a5063aa75b3b.png">

And I've checked the syntax highlighting by testing it with the [one of the strings](https://github.com/tonsky/sublime-clojure/blob/master/syntax_test_clojure.cljc#L124) from your testing files. Before:

<img width="570" alt="Captura de pantalla 2019-09-16 a las 16 39 55" src="https://user-images.githubusercontent.com/6537798/64962811-c734bd00-d8a0-11e9-95bc-c598025c87cc.png">

Now:

<img width="572" alt="Captura de pantalla 2019-09-16 a las 16 39 28" src="https://user-images.githubusercontent.com/6537798/64962821-cc920780-d8a0-11e9-9d30-76c5a2c28b45.png">

And of course everything works properly with sending selected code into REPL.

I'm not sure whether it's a big deal or not, because I haven't had any Clojure experience yet, but when I googled plugins for REPL I got an impression that this one is the most popular for this purpose. So maybe you need to improve the docs by adding Troubleshooting section.

**Comment by tonsky** [comment]
Sublime-clojure does not provide repl. You need a separate plugin for that (like SublimeREPL). What do you think I should change in the documentation?

**Comment by igoradamenko** [comment]
Yes, of course I understand that it doesn't provide a REPL.

I thought that you could add a note about SublimeREPL Clojure's REPL which breaks because of installing sublime-clojure. And I thought it would be worth to note that sublime-clojure can fix highlighting not only inside Sublime Text but inside SublimeREPL too.

So, it's not an issue “because sublime-clojure doesn't work”, it's “because it can be a bit friendly”.

But maybe I'm wrong and it doesn't worth to be noted. Feel free to close the issue in this case.

**Comment by tonsky** [comment]
Sorry, I didn’t understand what you were doing. So you enabled sublime-clojure for SublimeREPL. Now I get it. Yes of course it’s useful

**Comment by tonsky** [comment]
Added to README. Thanks!
