### ISSUE TITLE
Plugin appears to not exist in package control

### ISSUE THREAD

**Issue by trafnar** [tonsky/sublime-clojure#27]
I don't find the plugin listed when I search for `sublime clojure` in package control.

Am I missing it, or shouldn't it appear here? https://packagecontrol.io/search/Sublime%20Clojure

**Comment by trafnar** [comment]
My mistake, I didn't see that it said "coming soon"

**Comment by tonsky** [comment]
You can track progress here https://github.com/wbond/package_control_channel/pull/8394
Unfortunately it takes time
