### ISSUE TITLE
Evaluating without selection doesn't evaluate topmost form

### ISSUE THREAD

**Issue by trafnar** [tonsky/sublime-clojure#33]
I'm new to clojure, sorry if this is a misguided question.

The basic "Clojure REPL: Evaluate" command seems to try to evaluate only the character at my cursor, not the top most form. Any idea what is wrong with my setup, or if this is some kind of bug?

With my cursor between `(` and `+` I get this result:
![image](https://user-images.githubusercontent.com/6732/141874242-78d10c4b-a61c-4a5c-9a2d-4b9aee8b7407.png)

With the entire line selected, I get `2`

**Comment by tonsky** [comment]
Interesting!

Have you set syntax to `Clojure (Sublime Clojure)`?

**Comment by trafnar** [comment]
Oh, that was the problem! I did see that in the docs, an I thought I had set it appropriately, but I guess not. Thanks for the help.

**Comment by tonsky** [comment]
Yeah, it’s a thing that’s too easy to miss. Eventually I hope I get rid of this limitation
