### ISSUE TITLE
Keystroke for REPL connect that includes port auto-detection?

### ISSUE THREAD

**Issue by pmonks** [tonsky/sublime-clojure#41]
I enabled the following keystroke, and while it works, the port auto-detection logic doesn't seem to fire so I have to manually type the port into the little command window that pops up.  Is it possible to fire the command from a keystroke, but have it auto-detect the port number, as happens when this command is run manually via the command palette?

In my user keymap file:
```json
    {"keys": ["ctrl+j"],
     "command": "sublime_clojure_connect"},
```

**Comment by tonsky** [comment]
Works for me. It works like this:

- Finds an active ST window
- Looks in each _top-level_ folder open
- If any of them have `.nrepl-port` file _at the top level_, uses it for auto-substitution.

Do you have this file? Does it contain the port number? Which OS are you on? Are there any errors in the ST console (ctrl+tilde)? Can you record a screencast?

**Comment by pmonks** [comment]
Yeah it's working for me now too. Not sure why it didn't work previously - perhaps I didn't have the folder with the `.nrepl-port` file open?  Not sure...
